#!/bin/bash

if [ $# -gt 3 ]
then
	echo $"./intra_pred [ intra_config [ n_dir [ n_exec] ] ]"
	exit
fi

if [ ! -d $"log" ]
then
	mkdir $"log"
fi
if [ $# = 3 ]
then
	n_exec=$3;
	n=$2;
else if [ $# = 2 ]
	then
		n_exec=1;
		n=$2;
	else
		n_exec=1;
		n=0;
		while [ -d $"log/log_$n" ]
		do
			n=$(( $n+1 ));
		done
	fi
fi
mkdir $"log/log_$n"

if [ $# = 1 ] || [ $# = 2 ] || [ $# = 3 ]
then
	conf_name=$1;
else
	conf_name=intra_config.cfg
fi
exec 0< $conf_name
	
read line
read line
for image in $(echo $line | tr ";" "\n")
do
	./pred_image $image $"log/log_$n" $conf_name $n_exec
	code=$?
	if [ $code != 0 ]
	then
		echo $"Program return code: $code"
		exit $code
	fi
done

notify-send $conf_name Computaion\ completed
