#!/bin/bash

if [ $# -ne 1 ]
then
	if [ $# -eq 0 ]
	then
		n_copy=1
	else
		echo $"makevar [n_var]"
		exit
	fi
else
	if [ $1 = $"clean" ]
	then
		make clean
		rm ./wavedec*
		exit
	else
		n_copy=$1
	fi
fi

if [ $n_copy -eq 1 ]
then
	execname=$"./wavedec"
else
	execname=$"./wavedec_$n_copy"
fi

make
mv ./wavedec_var $execname
