#!/bin/bash
exec 0< $5
read line; read line
read line; read line
read line; read line
read line; read line

if [ $6 = 1 ]
then
	name_exec=$"./wavedec";
else
	name_exec=$"./wavedec_$6";
fi

for qf in $(echo $line | tr ";" "\n")
do
# using filter number instead of block size
#	$name_exec $1 0 $2 $3 $qf $"config.cfg" $4
	$name_exec $1 $2 0 $3 $qf $"config.cfg" $4
	code=$?
	if [ $code != 0 ]
	then
		exit $code
	fi
done
