#!/bin/bash
exec 0< $4
read line; read line
read line; read line
read line; read line
for mode in $(echo $line | tr ";" "\n")
do
	./pred_qf $1 $2 $mode $3 $4 $5
	code=$?
	if [ $code != 0 ]
	then
		exit $code
	fi
done
